# Generated by Django 3.2.7 on 2022-03-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlisting_bids_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='listingImage',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='listingName',
            new_name='Title',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='Category',
            field=models.CharField(choices=[('TECH', 'Technology'), ('FASH', 'Fashion'), ('AUTO', 'Automotive'), ('TOOL', 'Tools'), ('MEDI', 'Media')], default=None, max_length=4),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='Description',
            field=models.CharField(default='No description yet', max_length=500),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='startingBid',
            field=models.IntegerField(default=0),
        ),
    ]
