# Generated by Django 3.2.7 on 2022-03-29 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20220329_1104'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bids',
            new_name='bid',
        ),
        migrations.RenameModel(
            old_name='comments',
            new_name='comment',
        ),
    ]
