# Generated by Django 3.2.7 on 2022-03-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auctionlisting_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='Category',
            field=models.CharField(choices=[('TECH', 'Technology'), ('FASH', 'Fashion'), ('AUTO', 'Automotive'), ('TOOL', 'Tools'), ('MEDI', 'Media')], default='None', max_length=4),
        ),
    ]
