# Generated by Django 3.2.7 on 2022-03-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auctionlisting_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='Category',
            field=models.CharField(choices=[('NONE', 'None'), ('TECH', 'Technology'), ('FASH', 'Fashion'), ('AUTO', 'Automotive'), ('TOOL', 'Tools'), ('MEDI', 'Media')], default='NONE', max_length=4),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='startingBid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
