# Generated by Django 3.2.7 on 2022-04-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20220330_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='Description',
            field=models.CharField(max_length=500),
        ),
    ]
