# Generated by Django 3.2.7 on 2022-06-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20220626_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='Category',
            field=models.CharField(choices=[('None', 'None'), ('Tech', 'Technology'), ('Fashion', 'Fashion'), ('Automotive', 'Automotive'), ('Tools', 'Tools'), ('Media', 'Media')], default='None', max_length=30),
        ),
    ]
