# Generated by Django 3.2.7 on 2022-06-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_auctionlisting_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='shortDescription',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
