# Generated by Django 3.2.7 on 2022-06-26 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auctionlisting_shortdescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='shortDescription',
            new_name='Blurb',
        ),
    ]
