# Generated by Django 3.2.7 on 2022-06-26 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_rename_shortdescription_auctionlisting_blurb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='startingBid',
            new_name='starting_Bid',
        ),
    ]
