# Generated by Django 3.2.7 on 2022-07-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='currentBid',
        ),
        migrations.AddField(
            model_name='bid',
            name='newBid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
