# Generated by Django 3.2.7 on 2022-07-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20220702_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='newBid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
