# Generated by Django 3.2.7 on 2022-07-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_bid_newbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='newBid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11),
        ),
    ]
