# Generated by Django 3.2.7 on 2022-07-14 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_alter_bid_newbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='onListing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='onListing', to='auctions.auctionlisting'),
            preserve_default=False,
        ),
    ]
