# Generated by Django 3.2.7 on 2022-07-17 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_alter_bid_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='auctions.auctionlisting'),
            preserve_default=False,
        ),
    ]
