# Generated by Django 3.2.7 on 2022-07-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0029_auctionlisting_currentbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='currentBid',
            field=models.DecimalField(blank=True, decimal_places=2, default=models.DecimalField(decimal_places=2, default=0, max_digits=10), max_digits=10, null=True),
        ),
    ]
