# Generated by Django 3.2.7 on 2022-07-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0030_alter_auctionlisting_currentbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='currentBid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
