# Generated by Django 3.2.7 on 2022-07-24 06:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_alter_auctionlisting_currentbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bidTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
