# Generated by Django 3.2.7 on 2022-10-18 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_auto_20221017_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='Price',
        ),
    ]
