# Generated by Django 3.2.7 on 2022-10-18 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0035_remove_auctionlisting_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='auction',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='bidTime',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='newBid',
        ),
    ]
