# Generated by Django 3.2.7 on 2022-10-26 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0038_auctionlisting_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentText',
            field=models.CharField(default='test comment', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='auctions.auctionlisting'),
        ),
    ]
