# Generated by Django 3.2.7 on 2022-11-03 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0041_bid_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='currentBid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid', to='auctions.bid'),
        ),
    ]
